server:
  port: 8084

spring:
  application:
    name: zm-mq-service
  activemq:
    broker-url: tcp://192.168.99.128:61616
    user: admin
    password: admin
    in-memory: false
    packages:
      trust-all: true
    pool:
      enabled: false
    send-timeout: 0ms
  kafka:
    bootstrap-servers: 192.168.99.128:9092
    consumer:
      group-id: test-consumer-group
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
    listener:
      missing-topics-fatal: false
      concurrency: 5
      type: batch
    producer:
      batch-size: 4096
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


rocketmq:
  name-server: 192.168.99.128:9876
  producer:
    group: ${spring.application.name}
