server:
  port: 8084
spring:
  activemq:
    broker-url: tcp://192.168.99.128:61616
    user: admin
    password: admin
    in-memory: false #\u662F\u5426\u9ED8\u8BA4\u5185\u5B58\u4EE3\u7406URL
    packages:
      trust-all: true
    pool:
      enabled: false #\u662F\u5426\u91C7\u7528pool\u7684factory
#     use-anonymous-producers: true #\u53EA\u4F7F\u7528\u4E00\u4E2Aproducer
#      close-timeout: 15s # \u7ED3\u675F\u524D\u7B49\u5F85\u65F6\u95F4\uFF0C\u9ED8\u8BA415s
    send-timeout: 0ms #
#  jms:
#    pub-sub-domain: false #\u63A8\u9001\u6A21\u5F0F\uFF1Afalse-queue\uFF0Ctrue-topoc
