server:
  port: 8084
spring:
  activemq:
    broker-url: tcp://192.168.88.128:61616
    user: admin
    password: admin
    in-memory: false
    packages:
      trust-all: true
    pool:
      enabled: false
#  jms:
#    pub-sub-domain: false #false-queue  true-topoc  \u5168\u90FD\u8981\u5C31\u4E0D\u7528\u914D\u7F6E\u4E86